---

- name: add newrelic gpg keys
  ansible.builtin.rpm_key:
    state: present
    key: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg

- name: add newrelic repository
  ansible.builtin.get_url:
    url: "https://download.newrelic.com/infrastructure_agent/linux/yum/el/8/{{ ansible_architecture }}/newrelic-infra.repo"
    dest: /etc/yum.repos.d/newrelic.repo
    owner: root
    group: root
    mode: 0644

- name: install newrelic-infra
  ansible.builtin.dnf:
    name: newrelic-infra
    state: present

- name: disable newrelic-infra
  ansible.builtin.service: name=newrelic-infra enabled=no
  when: not newrelic_role_debug|bool
